### ISSUE TITLE
Questions about the conterfactual feature (Only zero vector is used, the other two are not given)

### ISSUE THREAD

**Issue by kevinlemon** [CHENGY12/CausalHTP#2]
Hi, this is an interesting work. Thanks for sharing the code.
However, in your code "models.py"  from line 255
"
 traj_lstm_hidden_states_c = torch.zeros_like(traj_lstm_hidden_states[-1])
"
It seems that only zero vector is used. The mean vector of all history trajectories or the random trajectories
are not shown here as the counterfactual intervention.
Could you explain that? Thank you

**Comment by jun-long-li** [comment]
Hi,

Thanks for your interest and question!

For the random one, when training the model, we replace this line with
`traj_lstm_hidden_states_c = (torch.rand(traj_lstm_hidden_states[-1].shape) - 0.5) / 5`
which uses a vector sampled from a uniform distribution with [−0.1, 0.1] as mentioned in the paper. Then use the expectation of uniform distribution (zero vector) in the testing stage.
For the mean vector, we first extract the features of all training trajectories with the pre-trained baseline encoder (e.g. pre-trained STGAT encoder) and get the mean vector from these features as the counterfactual values. Here we use the same  mean vector in both training and testing stage.

Hope this helps!
