### ISSUE TITLE
Question about visualization

### ISSUE THREAD

**Issue by Xiejc97** [CHENGY12/CausalHTP#3]
Hi,

Thank you very much for your work and I'm very interested in trajectory prediction.

I have some problems about the visualization of predicted trajectory. How to plot the trajectories in the scene picture just like the Fig5(https://github.com/CHENGY12/CausalHTP/blob/main/images/examples_social-stgat.png) in your paper?

Can you share with me the code for the visualization of the trajectories please? Thank you very much!

**Comment by jun-long-li** [comment]
Hi,

Thanks for your interest and question!

We first plot the observed, predicted and ground-truth trajectories in a figure without physical scenes. The code is based on [https://github.com/huang-xx/STGAT/blob/master/STGAT/draw_trajectory.py](url) and we'll soon update this code. With this figure, we look for the corresponding frame in the original video, where the pedestrians are at the last observed positions. Then we incorporate the figure and the corresponding frame by matching the trajectories to pedestrians.

**Comment by cxc1219** [comment]
Hi,
I have the same problems about the visualization. you said : look for the corresponding frame in the original video, can you tell me where to download the video. I have looked for a long time.

**Comment by jun-long-li** [comment]
BIWI Walking Pedestrians dataset (ETH): [https://data.vision.ee.ethz.ch/cvl/aem/ewap_dataset_full.tgz](url)
UCY: [https://graphics.cs.ucy.ac.cy/research/downloads/crowd-data](url)

**Comment by wangwen39** [comment]
I have the same problem about the visualization, would you please update your code? Looking forward to your reply~

**Comment by SWORD0731** [comment]
Hello, I would like to ask, after drawing continuous points with plt, how can I accurately correspond to the points in the video? Visual inspection? 感谢大佬
